"""Constants for Telecom feature timeouts and delays."""

import datetime

# --- General Timeouts ---
POLLING_INTERVAL = datetime.timedelta(seconds=1)
DELAY_STANDARD = datetime.timedelta(seconds=3)
TIMEOUT_QUICK = datetime.timedelta(seconds=5)
TIMEOUT_SHORT = datetime.timedelta(seconds=10)
TIMEOUT_STABLE = datetime.timedelta(seconds=15)
TIMEOUT_MEDIUM = datetime.timedelta(seconds=20)
TIMEOUT_LONG = datetime.timedelta(seconds=30)
TIMEOUT_MAX = datetime.timedelta(seconds=60)

# --- Call State Timeouts ---
WAIT_CALL_CONNECTED_TIMEOUT = TIMEOUT_LONG
WAIT_CALL_DISCONNECTED_TIMEOUT = TIMEOUT_MEDIUM
WAIT_CALL_RINGING_TIMEOUT = TIMEOUT_LONG
WAIT_CALL_DAILING_TIMEOUT = TIMEOUT_LONG
WAIT_CALL_AUDIO_STATE_TIMEOUT = TIMEOUT_STABLE

# --- UI & Action Delays ---
DELAY_BETWEEN_ACTIONS = POLLING_INTERVAL
DELAY_BETWEEN_CALL_STATE_CHECKS = POLLING_INTERVAL
WAIT_SCREEN_LOCK_TIMEOUT = TIMEOUT_SHORT
UI_WAIT_TIME = DELAY_STANDARD
UI_PERMISSION_WAIT_TIME = TIMEOUT_SHORT
AUDIO_CALL_BUTTON_WAIT_TIME = TIMEOUT_QUICK
AUDIO_STATE_PREPARE_TIMEOUT = DELAY_STANDARD
AUDIO_CLARITY_VERIFY_TIMEOUT = DELAY_STANDARD
AUDIO_VERIFY_TIMEOUT = datetime.timedelta(seconds=10)
