"""Utils for operating account on an Android device."""

import datetime
import logging
import time
from typing import Any

from mobly import asserts
from mobly.controllers import android_device
from mobly.snippet import errors as snippet_errors
import tenacity

from android_telecq.bluetooth.utils import test_utils


_MH_TAG = 'mh_test_properties'
_MH_APS_EMAIL = 'android_account_decorator_emails'
_MH_APS_PASSWORD = 'android_account_decorator_passwords'
_MPT_EMAIL = 'test_account_emails'
_MPT_PASSWORD = 'test_account_passwords'

_WAIT_FOR_ACCOUNT_CHANGED = datetime.timedelta(seconds=120)
_WAIT_FOR_UI_EXISTS = datetime.timedelta(seconds=10)
_UI_CHANGE_DELAY = datetime.timedelta(seconds=1)


def list_emails(
    user_params: dict[str, Any], ignore_raise_on_empty: bool = False
) -> list[str]:
  """Gets all emails controlled by AccountProviderService."""
  if _MPT_EMAIL in user_params:
    email = user_params[_MPT_EMAIL]
    return email if isinstance(email, list) else email.split(',')
  if _MH_TAG in user_params and _MH_APS_EMAIL in user_params[_MH_TAG]:
    return user_params[_MH_TAG][_MH_APS_EMAIL].split(',')
  asserts.assert_true(
      ignore_raise_on_empty,
      'No email is assigned to AccountProviderService, check BUILD file',
  )
  return []


def list_passwords(user_params: dict[str, Any]) -> list[str]:
  """Gets all passwords generated by AccountProviderService."""
  if _MPT_PASSWORD in user_params:
    password = user_params[_MPT_PASSWORD]
    return password if isinstance(password, list) else password.split(',')
  if _MH_TAG in user_params and _MH_APS_PASSWORD in user_params[_MH_TAG]:
    return user_params[_MH_TAG][_MH_APS_PASSWORD].split(',')
  asserts.fail(
      'No password is refreshed by AccountProviderService, check BUILD file'
  )


@tenacity.retry(
    stop=tenacity.stop_after_attempt(3),
    wait=tenacity.wait_exponential(multiplier=1, max=10),
    before_sleep=tenacity.before_sleep_log(
        logging.getLogger(__name__), logging.INFO
    ),
)
def login_accounts(
    ad: android_device.AndroidDevice,
    user_params: dict[str, Any],
    timeout: datetime.timedelta = _WAIT_FOR_ACCOUNT_CHANGED,
) -> list[str]:
  """Logs in all accounts specified in user_params and waits for success."""
  emails = list_emails(user_params)
  if not emails:
    ad.log.info('No accounts to login.')
    return []

  passwords = list_passwords(user_params)
  for email, password in zip(emails, passwords):
    ad.bt_snippet.addAccount(email, password)

  emails_set = set(emails)
  error_msg = (
      f'[AndroidDevice|{ad.debug_tag}] Failed to add accounts after'
      f' {timeout.total_seconds()} seconds'
  )
  test_utils.wait_until_or_assert(
      lambda: emails_set.issubset(set(ad.bt_snippet.getAccountEmails())),
      error_msg,
      timeout,
  )
  ad.log.info(f'Accounts {emails_set} logged in successfully.')
  return emails


def remove_accounts(
    ad: android_device.AndroidDevice,
    timeout: datetime.timedelta = _WAIT_FOR_ACCOUNT_CHANGED,
) -> None:
  """Removes all accounts and waits until removal is successful."""
  ad.log.info('Removing all accounts...')

  # Try using AccountSnippet first
  try:
    ad.bt_snippet.removeAllAccounts()
  except snippet_errors.Error as e:
    ad.log.exception('Failed to remove accounts via AccountSnippet: %s', e)

  def _is_all_accounts_removed() -> bool:
    """Returns true if all accounts are removed."""
    emails = ad.bt_snippet.getAccountEmails()
    if not emails:
      return True

    ad.log.info('Accounts remaining: %s. Attempting UI removal.', emails)
    for email in emails:
      if not email.endswith('@gmail.com'):
        continue

      ad.adb.shell('am start -S -W -a android.settings.SYNC_SETTINGS')
      # Wait for the account list to load and click the target account
      target_account = ad.uia(textMatches=f'(?i).*{email}.*')
      if target_account.click.wait(_WAIT_FOR_UI_EXISTS):
        time.sleep(_UI_CHANGE_DELAY.total_seconds())
        # Click "Remove account" button
        remove_button = ad.uia(textMatches='(?i).*Remove account.*')
        if remove_button.click.wait(_WAIT_FOR_UI_EXISTS):
          time.sleep(_UI_CHANGE_DELAY.total_seconds())
          # Click "Remove account" in the confirmation dialog
          confirm_button = ad.uia(
              textMatches='(?i).*Remove account.*',
              resourceIdMatches='.*button1.*|.*ok.*|.*confirm.*',
          )
          if confirm_button.click.wait(_WAIT_FOR_UI_EXISTS):
            time.sleep(_UI_CHANGE_DELAY.total_seconds())
      ad.adb.shell('am force-stop com.android.settings')
      time.sleep(1)
    return not ad.bt_snippet.getAccountEmails()

  error_msg = (
      f'[AndroidDevice|{ad.debug_tag}] Failed to remove all accounts after'
      f' {timeout.total_seconds()} seconds'
  )
  test_utils.wait_until_or_assert(
      condition=_is_all_accounts_removed,
      error_msg=error_msg,
      timeout=timeout,
  )
  ad.log.info('All accounts removed successfully.')
